on: [push]
jobs:
    build:
        runs-on: docker
        steps:
            - uses: https://code.forgejo.org/actions/checkout@v6
            - run: apt-get update -qq
            - run: apt-get -q install -y -qq npm
            - uses: https://git.ryujinx.app/actions/setup-dotnet@v5
              with:
                dotnet-version: '9.0.x'
            - run: cp gex/env.template.json gex/env.json
            - run: cp gex/secrets.template.json gex/secrets.json
            - run: dotnet build gex/gex.sln --self-contained -c Release -p:RuntimeWorkaround=linux-x64
            - run: |
                cd gex
                npm run watch

