using gex.Models.Db;
using gex.Models.MapStats;
using gex.Services.Db.Map;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace gex.Services.Repositories {

    public class MapStatsStartSpotRepository {

        private readonly ILogger<MapStatsStartSpotRepository> _Logger;
        private readonly MapStatsStartSpotDb _Db;
        private readonly IMemoryCache _Cache;

        private const string CACHE_KEY_BY_USER = "Gex.MapStats.User.StartSpot.{0}"; // {0} => cache key generated by obj

        public MapStatsStartSpotRepository(ILogger<MapStatsStartSpotRepository> logger,
            MapStatsStartSpotDb db, IMemoryCache cache) {

            _Logger = logger;
            _Db = db;
            _Cache = cache;
        }

        public Task<List<MapStatsStartSpot>> GetByMap(string mapFilename, CancellationToken cancel) {
            return _Db.GetByMap(mapFilename, cancel);
        }

        public Task Generate(string mapFilename, CancellationToken cancel) {
            return _Db.Generate(mapFilename, cancel);
        }

        public async Task<List<MapStatsStartSpot>> GetByMapAndUser(UserStartSpotSearchParameters parameters, CancellationToken cancel) {

            if (parameters.UserID == 0) {
                throw new ArgumentException($"{nameof(UserStartSpotSearchParameters.UserID)} cannot be 0");
            }
            if (string.IsNullOrWhiteSpace(parameters.MapFilename) == true) {
                throw new ArgumentException($"{nameof(UserStartSpotSearchParameters.MapFilename)} cannot be empty");
            }

            string cacheKey = string.Format(CACHE_KEY_BY_USER, parameters.GetCacheKey());
            if (_Cache.TryGetValue(cacheKey, out List<MapStatsStartSpot>? startSpots) == false || startSpots == null) {
                startSpots = await _Db.GetByMapAndUser(parameters, cancel);

                _Cache.Set(cacheKey, startSpots, new MemoryCacheEntryOptions() {
                    AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(10)
                });
            }

            return startSpots;
        }

    }
}
